project:
  type: website
  output-dir: docs

website:
  title: Rep2SI
  navbar:
    background: primary
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Team"
        file: team.qmd 
#      - text: "Blog"
#        file: blog.qmd
      - text: "Contact"
        file: contact.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



